import React, { useState, useEffect, createContext, useContext } from 'react';
import * as Commons from './Commons';
import * as Constants from './Constants';

export const STRINGS = {
    en: {
        no_branches: 'No branches added yet',
        remove_service: 'Remove Service',
        remove_service_confirm: 'Are you sure you want to remove this service?',
        remove_branch: 'Remove Branch',
        remove_branch_confirm: 'Are you sure you want to remove this branch?',
        remove_subscription: 'Remove Subscription',
        remove_subscription_confirm: 'Are you sure you want to remove this subscription plan?',
        remove_promo: 'Remove Promo',
        remove_promo_confirm: 'Are you sure you want to remove this promo?',
        remove_btn: 'Remove',
        verifying: 'Verifying...',
        verify_register: 'Verify & Register',
        user_info: 'User Info',
        settings: 'Settings',
        add_new_plan: '+ Add New Plan',
        period: 'Period',
        fee_jod: 'Fee (JOD)',
        jod: 'JOD',
        no_subscription_plans: 'No subscription plans added yet',
        failed_save_changes: 'Failed to save changes',
        gyms: 'Gyms',
        gyms_found: '{count} gyms found',
        no_gyms_found: 'No gyms found',
        branch_id: 'Branch ID',
        area: 'Area',
        location_latlong: 'Location (Lat,Long)',
        media_urls: 'Media (URLs)',
        manage_locations: 'Manage your gym locations',
        add_new_branch: '+ Add New Branch',
        enter_branch_id: 'Enter branch ID',
        enter_area_name: 'Enter area name',
        enter_location_latlong: 'e.g., 31.9454,35.9284',
        enter_media_urls: 'Enter media URLs separated by commas',
        mens_section_from: "Men's Section From (Time)",
        mens_section_to: "Men's Section To (Time)",
        mixed_section: 'Mixed Section (Y/N)',
        mixed: 'Mixed',
        not_mixed: 'Not Mixed',
        womens_section_from: "Women's Section From (Time)",
        womens_section_to: "Women's Section To (Time)",
        womens_available: "Women's Section",
        gym_management: 'Gym Management',
        general_information: 'General Information',
        manage_gym_basic: "Manage your gym's basic details",
        quick_overview: 'Quick Overview',
        branches: 'Branches',
        services_text: 'Services',
        plans: 'Plans',
        save_changes: 'Save Changes',
        cancel: 'Cancel',
        uploading_photo: 'Uploading photo...',
        tap_change_photo: 'Tap to change photo',
        email_cannot_change: 'Email cannot be changed',
        username_cannot_change: "Username cannot be changed",
        name_required: 'Name cannot be empty',
        profile_updated: 'Profile updated successfully!',
        upload_failed: 'Failed to upload image to server.',
        upload_failed_title: 'Upload Failed',
        need_camera_roll_permissions: 'Sorry, we need camera roll permissions to add images.',
        failed_pick_or_upload_image: 'Failed to pick or upload image',
        failed_load_gyms_try_again: 'Failed to load gyms. Please try again.',
        failed_load_gyms_check_connection: 'Failed to load gyms. Please check your connection.',
        failed_load_gym_data: 'Failed to load gym data',
        services_updated: 'Services updated successfully',
        failed_update_profile_try_again: 'Failed to update profile. Please try again.',
        image_picker_timeout: 'Image picker timed out. Please try again.',
        ok: 'OK',
        remove_image: 'Remove image',
        long_press_to_remove: 'Long-press to remove image',
        remove_image_confirm: 'Are you sure you want to remove this image?',
        available_until: 'Available until',
        subscribe: 'Subscribe',
        start_date: 'Start Date',
        start_date_required: 'Please select a start date',
        pick_start_date: 'Pick Start Date',
        subscription_success: 'Subscription successful',
        subscription: 'Subscription',
        promo: 'Promo',
        subscription_failed: 'Subscription failed. Please try again.',
        please_login: 'Please login to continue',
        yes: 'Yes',
        file_error: 'File Error',
        audio_file_not_found: 'Audio file not found.',
        audio_file_empty: 'Audio file is empty.',
        playback_error: 'Playback Error',
        failed_to_load_audio: 'Failed to load audio file.',
        audio_file_corrupted: 'Audio file appears to be empty or corrupted.',
        failed_to_play_audio: 'Failed to play audio file. Error: {error}',
        cannot_open_file: 'Cannot open file',
        no_application_to_open_file: 'No application available to open this file.',
        failed_to_open_attachment: 'Failed to open attachment. Error: {error}',
        menu: 'Menu',
        logout: 'Logout',
        confirm_logout_title: 'Confirm Logout',
        confirm_logout_message: 'Are you sure you want to logout?',
        back_to_home: 'Back to Home',
        featured_gyms: 'Featured Gyms',
        browse_by_category: 'Browse by Category',
        nearby_gyms: 'Nearby Gyms',
        finding_nearest: 'Finding nearest gyms...',
        no_nearby: 'No nearby gyms found',
        choose_location: 'Choose location on map',
        search_place: 'Search place or address',
        confirm: 'Confirm',
        failed_load_map: 'Failed to load map. Please try again',
        use_current_location: 'Use current location',
        use_current_location_hint: 'Center map on your current device location',
        getting_location: 'Getting location...',
        failed_get_location: 'Failed to get current location. Check permissions or try again.',
        turn_on_location_services: 'Turn on location services in Settings to see nearby gyms',
        open_settings: 'Open Settings',
        enable_location: 'Enable Location',
        location_permission_denied: 'Location permission denied. Please allow location access to find nearby gyms',
        preferences: 'Preferences',
        passwords_mismatch: 'Passwords do not match',
        invalid_email: 'Please enter a valid email address',
        otp_sent: 'A verification code has been sent to your email',
        registration_success: 'Registration successful. Please log in.',
        registration_failed: 'Registration failed. Please try again.',
        invalid_otp: 'Invalid OTP. Please try again.',
        otp_resent: 'A new verification code has been sent to your email',
        save_changes: 'Save Changes',
        cancel: 'Cancel',
        select_a_service: 'Please choose a service from the provided list.',
        already_added: 'This service is already in your list.',
        please_fill_all_fields: 'Please fill in all fields',
        login_failed: 'Login failed. Please try again.',
        please_enter_email: 'Please enter an email',
        please_enter_email_username: 'Enter your email/username',
        enter_email_username: 'Enter your email/username',
        email_username: 'Email / Username',
        restore_password: 'Restore Password',
        confirm_email: 'Confirm email',
        enter_password: 'Enter your password',
        password_sent: 'Password sent to your email',
        failed_restore: 'Failed to restore password',
        preferences: 'Preferences',
        notifications: 'Notifications',
        receive_updates: 'Receive updates about new gyms and offers',
        available: 'Available',
        not_available: 'Not Available',
        location_services: 'Location Services',
        find_gyms_near: 'Find gyms near your location',
        language: 'Language',
        english: 'English',
        arabic: 'العربية',
        about: 'About',
        privacy_policy: 'Privacy Policy',
        terms_of_service: 'Terms of Service',
        help_support: 'Help & Support',
        fitmap_version: 'Fitmap v1.0.0',
        welcome_back: 'Welcome Back',
        login_to_account: 'Login to your account',
        email: 'Email',
        username: 'Username',
        password: 'Password',
        forgot_password: 'Forgot Password?',
        login: 'Login',
        dont_have_account: "Don't have an account?",
        register: 'Register',
        create_account: 'Create Account',
        join_fitmap: 'Join Fitmap to find your perfect gym',
        full_name: 'Full Name',
        enter_full_name: 'Enter your full name',
        name: 'Name',
        enter_name: 'Enter name',
        businesstype: 'Business Type',
        enter_businesstype: 'Enter business type',
        business_type: 'Business Type',
        enter_business_type: 'Enter business type',
        est_name: 'Establishment Name',
        enter_est_name: 'Enter establishment name',
        nat_id: 'National ID',
        enter_nat_id: 'Enter national ID',
        category: 'Category',
        enter_category: 'Enter category',
        free_entry_code: 'Free Entry Code',
        enter_free_entry_code: 'Enter free entry code',
        enter_email: 'Enter your email',
        phone: 'Phone',
        enter_phone: 'Enter your phone number',
        create_password: 'Create a password',
        confirm_password: 'Confirm your password',
        verification_code: 'Verification Code',
        enter_otp: 'Enter 4-digit OTP',
        already_have_account: 'Already have an account?',
        login_text: 'Login',
        sending: 'Sending...',
        resend_otp: "Didn't receive code? Resend OTP",
        send_verification_code: 'Send Verification Code',
        sending_otp: 'Sending OTP...',
        member_since: 'Member since',
        contact_information: 'Contact Information',
        edit_profile: 'Edit Profile',
        featured_gyms: 'Featured Gyms',
        browse_by_category: 'Browse by Category',
        nearby_gyms: 'Nearby Gyms',
        finding_nearest: 'Finding nearest gyms...',
        no_nearby: 'No nearby gyms found',
        services: 'Services',
        manage_services: 'Manage services offered at your gym',
        add_new_service: 'Add New Service',
        choose_service: 'Choose a service',
        current_services: 'Current Services',
        no_services: 'No services added yet',
        branches: 'Branches',
        manage_locations: 'Manage your gym locations',
        add_new_branch: '+ Add New Branch',
        branches_title: 'Branches',
        category_platinum: 'Platinum',
        category_platinum_desc: 'Premium facilities with world-class amenities and services',
        category_gold: 'Gold',
        category_gold_desc: 'High-quality gyms with excellent equipment and training programs',
        category_silver: 'Silver',
        category_silver_desc: 'Great gyms with essential amenities at affordable prices',
        category_bronze: 'Bronze',
        category_bronze_desc: 'Budget-friendly gyms perfect for basic fitness needs',
        gym: 'Gym',
        search_gyms_or_amenities: 'Search gyms or amenities...',
        search_services: 'Search services...',
        search_members: 'Search members...',
        search_gyms: 'Search Gyms',
        search_gyms_hint: 'Start typing or use filters to find gyms',
        filters: 'Filters',
        gym_location: 'Gym Location',
        enter_gym_location: 'Enter gym location...',
        service: 'Service',
        clear_filters: 'Clear Filters',
        apply: 'Apply',
        my_subscriptions: 'My Subscriptions',
        subscription_active: 'Active',
        subscription_inactive: 'Expired',
        subscription_for: 'Subscription for',
        no_subs_found: 'No subscriptions found',
        try_different_keyword: 'Try a different keyword or clear search',
        no_gyms_in_category: 'There are no gyms in this category right now.',
        promos: 'Promotions',
        no_promo: 'No promotions available',
        contact: 'Contact',
        loading_gym_data: 'Loading gym data...',
        saving_changes: 'Saving changes...',
        success: 'Success',
        general_info_updated: 'General information updated successfully',
        branches_updated: 'Branches updated successfully',
        subscriptions_updated: 'Subscriptions updated successfully',
        trainers_updated: 'Trainers updated successfully',
        promos_updated: 'Promos updated successfully',
        error: 'Error',
        email: 'Email',
        branch_number: 'Branch {number}',
        mens_section_from: "Men's Section From",
        mens_section_to: "Men's Section To",
        womens_section_from: "Women's Section From",
        womens_section_to: "Women's Section To",
        mixed_section: 'Mixed Section',
        time_format: 'e.g., 06:00',
        yes_no_format: 'Y or N',
        subscriptions: 'Subscriptions',
        manage_membership_plans: 'Manage membership plans and pricing',
        members: 'Members',
        manage_members: 'Manage members',
        no_members_added: 'No members found',
        member_name: 'Member Name',
        member_email: 'Email',
        member_phone: 'Phone',
        member_subscription_period: 'Subscription Period',
        member_price: 'Price',
        member_start_date: 'Start Date',
        member_end_date: 'End Date',
        plan_number: 'Plan {number}',
        no_price_set: 'No price set',
        price_format: 'e.g., 50',
        trainers: 'Trainers',
        manage_gym_trainers: 'Manage your gym trainers',
        add_trainer: '+ Add Trainer',
        enter_trainer_name: 'Enter trainer name',
        no_trainers_added: 'No trainers added yet',
        promos_title: 'Promos',
        manage_promotional_offers: 'Manage promotional offers',
        add_promo: '+ Add Promo',
        promo_number: 'Promo {number}',
        no_fee_set: 'No fee set',
        from_date: 'From Date',
        date_format: 'e.g., 01/12/2025',
        to_date: 'To Date',
        end_date_format: 'e.g., 31/12/2025',
        period: 'Period',
        period_format: 'e.g., 1 MONTH, 3 MONTHS',
        subscription_period: 'Subscription period',
        period_format_months: 'e.g., 1',
        month: 'month',
        months: 'months',
        fee_jod: 'Fee (JOD)',
        fee_format: 'e.g., 30',
        no_promos_added: 'No promos added yet',
        images: 'Images',
        view_on_map: 'View on Map',
        men_hours: 'Men Hours',
        women_hours: 'Women Hours',
    },
    ar: {
        no_branches: 'لم تتم إضافة فروع بعد',
        remove_service: 'إزالة الخدمة',
        remove_service_confirm: 'هل أنت متأكد أنك تريد إزالة هذه الخدمة؟',
        remove_branch: 'إزالة الفرع',
        remove_branch_confirm: 'هل أنت متأكد أنك تريد إزالة هذا الفرع؟',
        remove_subscription: 'إزالة الاشتراك',
        remove_subscription_confirm: 'هل أنت متأكد أنك تريد إزالة خطة الاشتراك هذه؟',
        remove_promo: 'إزالة العرض',
        remove_promo_confirm: 'هل أنت متأكد أنك تريد إزالة هذا العرض؟',
        remove_btn: 'إزالة',
        verifying: 'جاري التحقق...',
        verify_register: 'تحقق وسجل',
        user_info: 'معلومات المستخدم',
        settings: 'الإعدادات',
        add_new_plan: '+ أضف خطة جديدة',
        period: 'الفترة',
        fee_jod: 'السعر (دينار)',
        jod: 'دينار',
        no_subscription_plans: 'لم تتم إضافة خطط اشتراك بعد',
        failed_save_changes: 'فشل في حفظ التغييرات',
        gyms: 'نوادي',
        gyms_found: '{count} نادي',
        no_gyms_found: 'لم يتم العثور على نوادي',
        branch_id: 'اسم الفرع',
        area: 'المساحة',
        location_latlong: 'الموقع (خط العرض، خط الطول)',
        media_urls: 'ميديا (روابط)',
        manage_locations: 'إدارة مواقع النادي',
        add_new_branch: '+ أضف فرع جديد',
        enter_branch_id: 'أدخل اسم الفرع',
        enter_area_name: 'أدخل المساحة',
        enter_location_latlong: 'مثال: 31.9454,35.9284',
        enter_media_urls: 'أدخل رابط ميديا',
        mens_section_from: 'قسم الرجال من (الوقت)',
        mens_section_to: 'قسم الرجال إلى (الوقت)',
        mixed_section: 'قسم مختلط (Y/N)',
        mixed: 'مختلط',
        not_mixed: 'غير مختلط',
        womens_section_from: 'قسم النساء من (الوقت)',
        womens_section_to: 'قسم النساء إلى (الوقت)',
        womens_available: 'قسم خاص للنساء',
        gym_management: 'إدارة النادي',
        general_information: 'معلومات عامة',
        manage_gym_basic: 'إدارة التفاصيل الأساسية للنادي',
        quick_overview: 'نظرة سريعة',
        branches: 'الفروع',
        services_text: 'الخدمات',
        plans: 'الخطط',
        save_changes: 'حفظ التغييرات',
        cancel: 'إلغاء',
        uploading_photo: 'جارٍ تحميل الصورة...',
        tap_change_photo: 'انقر لتغيير الصورة',
        email_cannot_change: 'لا يمكن تغيير البريد الإلكتروني',
        username_cannot_change: 'لا يمكن تغيير اسم المستخدم',
        name_required: 'لا يمكن أن يكون الحقل فارغًا',
        profile_updated: 'تم تحديث الملف الشخصي بنجاح!',
        upload_failed: 'فشل تحميل الصورة إلى الخادم.',
        upload_failed_title: 'فشل التحميل',
        need_camera_roll_permissions: 'عذراً، نحتاج إلى إذن الوصول لمعرض الصور لإضافة الصور.',
        failed_pick_or_upload_image: 'فشل في اختيار أو رفع الصورة',
        failed_load_gyms_try_again: 'فشل تحميل النوادي. حاول مرة أخرى.',
        failed_load_gyms_check_connection: 'فشل تحميل النوادي. يرجى التحقق من اتصالك.',
        failed_load_gym_data: 'فشل تحميل بيانات النادي',
        services_updated: 'تم تحديث الخدمات بنجاح',
        failed_update_profile_try_again: 'فشل في تحديث الملف الشخصي. حاول مرة أخرى.',
        image_picker_timeout: 'انتهى وقت اختيار الصورة. حاول مرة أخرى.',
        ok: 'حسناً',
        remove_image: 'إزالة الصورة',
        long_press_to_remove: 'اضغط مطولاً لحذف الصورة',
        remove_image_confirm: 'هل أنت متأكد أنك تريد إزالة هذه الصورة؟',
        available_until: 'متوفر حتى',
        subscribe: 'اشترك',
        start_date: 'تاريخ البدء',
        start_date_required: 'الرجاء اختيار تاريخ البدء',
        pick_start_date: 'اختر تاريخ البدء',
        subscription_success: 'تم الاشتراك بنجاح',
        subscription_failed: 'فشل الاشتراك. حاول مرة أخرى.',
        subscription: 'اشتراك',
        promo: 'عرض',
        please_login: 'الرجاء تسجيل الدخول للمتابعة',
        yes: 'نعم',
        file_error: 'خطأ في الملف',
        audio_file_not_found: 'ملف الصوت غير موجود.',
        audio_file_empty: 'ملف الصوت فارغ.',
        playback_error: 'خطأ في التشغيل',
        failed_to_load_audio: 'فشل تحميل ملف الصوت.',
        audio_file_corrupted: 'يبدو أن ملف الصوت فارغ أو تالف.',
        failed_to_play_audio: 'فشل تشغيل ملف الصوت. الخطأ: {error}',
        cannot_open_file: 'لا يمكن فتح الملف',
        no_application_to_open_file: 'لا يوجد تطبيق لفتح هذا الملف.',
        failed_to_open_attachment: 'فشل فتح المرفق. الخطأ: {error}',
        menu: 'القائمة',
        logout: 'تسجيل الخروج',
        confirm_logout_title: 'تأكيد تسجيل الخروج',
        confirm_logout_message: 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
        back_to_home: 'العودة للرئيسية',
        featured_gyms: 'النوادي المميزة',
        browse_by_category: 'تصفح حسب الفئة',
        nearby_gyms: 'النوادي القريبة',
        finding_nearest: 'جاري العثور على أقرب النوادي...',
        no_nearby: 'لم يتم العثور على صالات قريبة',
        choose_location: 'اختر الموقع على الخريطة',
        search_place: 'ابحث عن مكان أو عنوان',
        confirm: 'تأكيد',
        failed_load_map: 'فشل تحميل الخريطة. حاول مرة أخرى',
        use_current_location: 'استخدم الموقع الحالي',
        use_current_location_hint: 'مركّز الخريطة على موقع جهازك الحالي',
        getting_location: 'جاري الحصول على الموقع...',
        failed_get_location: 'فشل في الحصول على الموقع الحالي. تحقق من الأذونات أو حاول مرة أخرى.',
        turn_on_location_services: 'قم بتشغيل خدمات الموقع لعرض الصالات القريبة',
        open_settings: 'افتح الإعدادات',
        enable_location: 'تمكين الموقع',
        location_permission_denied: 'تم رفض إذن الوصول إلى الموقع. يرجى السماح بالوصول للموقع لعرض النوادي القريبة',
        preferences: 'التفضيلات',
        passwords_mismatch: 'كلمة المرور غير متطابقة',
        invalid_email: 'يرجى إدخال بريد إلكتروني صالح',
        otp_sent: 'تم إرسال رمز التحقق إلى بريدك الإلكتروني',
        registration_success: 'تم التسجيل بنجاح. الرجاء تسجيل الدخول.',
        registration_failed: 'فشل التسجيل. حاول مرة أخرى.',
        invalid_otp: 'رمز تحقق غير صالح. حاول مرة أخرى.',
        otp_resent: 'تم إرسال رمز تحقق جديد إلى بريدك الإلكتروني',
        save_changes: 'حفظ التغييرات',
        cancel: 'إلغاء',
        select_a_service: 'يرجى اختيار خدمة من القائمة المتاحة.',
        already_added: 'هذه الخدمة موجودة بالفعل في قائمتك.',
        please_fill_all_fields: 'يرجى ملء جميع الحقول',
        login_failed: 'فشل تسجيل الدخول. حاول مرة أخرى.',
        please_enter_email: 'يرجى إدخال البريد الإلكتروني',
        restore_password: 'استعادة كلمة المرور',
        confirm_email: 'تأكيد البريد الإلكتروني',
        enter_password: 'أدخل كلمة المرور',
        password_sent: 'تم إرسال كلمة المرور إلى بريدك الإلكتروني',
        failed_restore: 'فشل استعادة كلمة المرور',
        preferences: 'التفضيلات',
        notifications: 'الإشعارات',
        receive_updates: 'تلقي التحديثات حول النوادي الرياضية والعروض',
        available: 'متاح',
        not_available: 'غير متاح',
        location_services: 'خدمات الموقع',
        find_gyms_near: 'ابحث عن النوادي الرياضية بالقرب من موقعك',
        language: 'اللغة',
        english: 'English',
        arabic: 'العربية',
        about: 'حول',
        privacy_policy: 'سياسة الخصوصية',
        terms_of_service: 'شروط الخدمة',
        help_support: 'المساعدة والدعم',
        fitmap_version: 'Fitmap v1.0.0',
        welcome_back: 'أهلا بك مجدداً',
        login_to_account: 'تسجيل الدخول إلى حسابك',
        email: 'البريد الإلكتروني',
        email_username: 'البريد الإلكتروني / اسم المستخدم',
        username: 'اسم المستخدم',
        password: 'كلمة المرور',
        forgot_password: 'هل نسيت كلمة المرور؟',
        login: 'تسجيل الدخول',
        dont_have_account: 'ليس لديك حساب؟',
        register: 'إنشاء حساب',
        create_account: 'إنشاء حساب',
        join_fitmap: 'انضم إلى Fitmap للعثور على صالتك المثالية',
        full_name: 'الاسم الكامل',
        enter_full_name: 'أدخل اسمك الكامل',
        name: 'الاسم',
        enter_name: 'أدخل الاسم',
        businesstype: 'نوع النشاط',
        enter_businesstype: 'أدخل نوع النشاط',
        business_type: 'نوع النشاط',
        enter_business_type: 'أدخل نوع النشاط',
        est_name: 'اسم المنشأة',
        enter_est_name: 'أدخل اسم المنشأة',
        nat_id: 'الهوية الوطنية',
        enter_nat_id: 'أدخل رقم الهوية الوطنية',
        category: 'الفئة',
        enter_category: 'أدخل الفئة',
        free_entry_code: 'كود الدخول المجاني',
        enter_free_entry_code: 'أدخل كود الدخول المجاني',
        enter_email: 'أدخل بريدك الإلكتروني',
        enter_email_username: 'أدخل بريدك الإلكتروني / اسم المستخدم',
        phone: 'الهاتف',
        enter_phone: 'أدخل رقم هاتفك',
        create_password: 'إنشاء كلمة مرور',
        confirm_password: 'تأكيد كلمة المرور',
        verification_code: 'رمز التحقق',
        enter_otp: 'أدخل رمز التحقق المكون من 4 أرقام',
        already_have_account: 'هل لديك حساب؟',
        login_text: 'تسجيل الدخول',
        sending: 'جاري الإرسال...',
        resend_otp: 'لم تستلم الرمز؟ أعد إرسال رمز التحقق',
        send_verification_code: 'إرسال رمز التحقق',
        sending_otp: 'جاري إرسال رمز التحقق...',
        member_since: 'عضو منذ',
        contact_information: 'معلومات الاتصال',
        edit_profile: 'تعديل الملف الشخصي',
        featured_gyms: 'النوادي المميزة',
        browse_by_category: 'تصفح حسب الفئة',
        nearby_gyms: 'النوادي القريبة',
        finding_nearest: 'جاري العثور على أقرب النوادي...',
        no_nearby: 'لم يتم العثور على صالات قريبة',
        services: 'الخدمات',
        manage_services: 'إدارة الخدمات المتاحة في صالتك',
        add_new_service: 'أضف خدمة جديدة',
        choose_service: 'اختر خدمة',
        current_services: 'الخدمات الحالية',
        no_services: 'لم تتم إضافة خدمات بعد',
        branches: 'الفروع',
        manage_locations: 'إدارة مواقع النادي',
        add_new_branch: '+ أضف فرع جديد',
        branches_title: 'الفروع',
        category_platinum: 'بلاتينيوم',
        category_platinum_desc: 'مرافق متميزة مع وسائل راحة وخدمات عالمية',
        category_gold: 'ذهبي',
        category_gold_desc: 'صالات عالية الجودة بمعدات وبرامج تدريب ممتازة',
        category_silver: 'فضي',
        category_silver_desc: 'صالات رائعة مع وسائل أساسية بأسعار معقولة',
        category_bronze: 'برونزي',
        category_bronze_desc: 'صالـات اقتصادية مثالية لاحتياجات اللياقة الأساسية',
        gym: 'نادي',
        gyms: 'نوادي',
        search_gyms_or_amenities: 'ابحث عن النوادي أو المرافق...',
        search_services: 'ابحث عن الخدمات...',
        search_members: 'ابحث عن الأعضاء...',
        search_gyms: 'البحث عن النوادي',
        search_gyms_hint: 'ابدأ الكتابة أو استخدم الفلاتر للعثور على النوادي',
        filters: 'الفلاتر',
        gym_location: 'موقع النادي',
        enter_gym_location: 'أدخل موقع النادي...',
        service: 'الخدمة',
        clear_filters: 'مسح الفلاتر',
        apply: 'تطبيق',
        my_subscriptions: 'اشتراكاتي',
        subscription_active: 'فعال',
        subscription_inactive: 'منتهي',
        subscription_for: 'اشتراك لـ',
        no_subs_found: 'لا توجد اشتراكات',
        try_different_keyword: 'جرب كلمة رئيسية مختلفة أو امسح البحث',
        no_gyms_in_category: 'لا توجد صالات في هذه الفئة في الوقت الحالي.',
        promos: 'العروض',
        no_promo: 'لا توجد عروض ترويجية متاحة',
        contact: 'اتصل',
        loading_gym_data: 'جاري تحميل بيانات النادي...',
        saving_changes: 'جاري حفظ التغييرات...',
        success: 'نجح',
        general_info_updated: 'تم تحديث المعلومات العامة بنجاح',
        branches_updated: 'تم تحديث الفروع بنجاح',
        subscriptions_updated: 'تم تحديث الاشتراكات بنجاح',
        trainers_updated: 'تم تحديث المدربين بنجاح',
        promos_updated: 'تم تحديث العروض بنجاح',
        error: 'خطأ',
        email: 'البريد الإلكتروني',
        email_username: 'البريد الإلكتروني / اسم المستخدم',
        branch_number: 'الفرع {number}',
        mens_section_from: 'قسم الرجال من',
        mens_section_to: 'قسم الرجال إلى',
        womens_section_from: 'قسم النساء من',
        womens_section_to: 'قسم النساء إلى',
        mixed_section: 'قسم مختلط',
        time_format: 'مثال: 06:00',
        yes_no_format: 'نعم/لا',
        subscriptions: 'الاشتراكات',
        manage_membership_plans: 'إدارة خطط العضوية والتسعير',
        members: 'الأعضاء',
        manage_members: 'إدارة الأعضاء',
        no_members_added: 'لم يتم العثور على أعضاء',
        member_name: 'اسم العضو',
        member_email: 'البريد الإلكتروني',
        member_phone: 'رقم الهاتف',
        member_subscription_period: 'مدة الاشتراك',
        member_price: 'السعر',
        member_start_date: 'تاريخ البدء',
        member_end_date: 'تاريخ الانتهاء',
        plan_number: 'الخطة {number}',
        no_price_set: 'لم يتم تحديد السعر',
        price_format: 'مثال: 50',
        trainers: 'المدربين',
        manage_gym_trainers: 'إدارة مدربي النادي',
        add_trainer: '+ أضف مدرب',
        enter_trainer_name: 'أدخل اسم المدرب',
        no_trainers_added: 'لم يتم إضافة مدربين بعد',
        promos_title: 'العروض',
        manage_promotional_offers: 'إدارة العروض',
        add_promo: '+ أضف عرض',
        promo_number: 'العرض {number}',
        no_fee_set: 'لم يتم تحديد السعر',
        from_date: 'من تاريخ',
        date_format: 'مثال: 01/12/2025',
        to_date: 'إلى تاريخ',
        end_date_format: 'مثال: 31/12/2025',
        period: 'الفترة',
        period_format: 'مثال: شهر واحد، 3 أشهر',
        subscription_period: 'مدة الاشتراك',
        period_format_months: 'مثال: 1',
        month: 'شهر',
        months: 'شهور',
        fee_jod: 'السعر (دينار)',
        fee_format: 'مثال: 30',
        no_promos_added: 'لم تتم إضافة عروض بعد',
        images: 'الصور',
        view_on_map: 'عرض على الخريطة',
        men_hours: 'ساعات الرجال',
        women_hours: 'ساعات النساء',
    }
};

// Hook to access translation
// Provide a TranslationContext so language change re-renders the whole app
export const TranslationContext = createContext({ locale: 'en', t: (k) => k, setLocale: () => { } });

export const TranslationProvider = ({ children }) => {
    const [locale, setLocale] = useState('ar');

    useEffect(() => {
        let mounted = true;
        (async () => {
            try {
                const saved = await Commons.getFromAS(Constants.language);
                const defaultLocale = 'ar';
                if (mounted) setLocale(saved || defaultLocale);
            } catch (e) {
                setLocale((await Commons.language()).substring(0, 2));
            }
        })();
        return () => (mounted = false);
    }, []);

    const t = (key) => {
        if (!key) return '';
        const lang = locale && STRINGS[locale] ? locale : 'en';
        return STRINGS[lang][key] || STRINGS['en'][key] || key;
    };

    const setLanguage = async (newLang) => {
        await Commons.saveToAS(Constants.language, newLang);
        setLocale(newLang);
    };

    return (
        <TranslationContext.Provider value={{ locale, t, setLanguage }}>{children}</TranslationContext.Provider>
    );
};

export const useTranslation = () => {
    const ctx = useContext(TranslationContext);
    if (ctx && ctx.t) return { t: ctx.t, locale: ctx.locale, setLanguage: ctx.setLanguage };

    // Fallback for components not wrapped in provider
    const [locale, setLocale] = useState('ar');
    useEffect(() => {
        let mounted = true;
        (async () => {
            try {
                const saved = await Commons.getFromAS(Constants.language);
                if (mounted) setLocale(saved || 'ar');
            } catch (e) {
                setLocale((await Commons.language()).substring(0, 2));
            }
        })();
        return () => (mounted = false);
    }, []);

    const t = (key) => {
        if (!key) return '';
        const lang = locale && STRINGS[locale] ? locale : 'en';
        return STRINGS[lang][key] || STRINGS['en'][key] || key;
    };

    const setLanguage = async (newLang) => {
        await Commons.saveToAS(Constants.language, newLang);
        setLocale(newLang);
    };

    return { t, locale, setLanguage };
};

export default STRINGS;
